export const ACTIONS = {
  LOAD_COMIC: 'LOAD_COMIC',
  LOAD_COMICS: 'LOAD_COMICS',
  LOAD_CHAPTER: 'LOAD_CHAPTER',
  LOAD_MOST_VIEWED_COMICS: 'LOAD_MOST_VIEWED_COMICS',
};
export const URLs = {
  SEARCH: '/comic/search',
};
