export const ACTIONS = {
  LOAD_COMIC: 'LOAD_COMIC',
  LOAD_COMICS: 'LOAD_COMICS',
  LOAD_CHAPTER: 'LOAD_CHAPTER',
  LOAD_MOST_VIEWED_COMICS: 'LOAD_MOST_VIEWED_COMICS',
  LOAD_COMIC_IN_PAGE: 'LOAD_COMIC_IN_PAGE',
  LOAD_ALL_COMICS_COUNT: 'LOAD_ALL_COMICS_COUNT',
  UPDATE_CURRENT_PAGE: 'UPDATE_CURRENT_PAGE',
  UPDATE_PAGE_COMICS: 'UPDATE_PAGE_COMICS',
};
